#!/usr/bin/env bash
set -e
pair=btcrub
sources=(
  binance
  bitstamp
  bittrex
  coinbase
  gemini
  kraken
  exmo
)

case $1 in
  binance | exmo) {
    btc_rub=$(setzer x-price "$1" btc:rub)
    setzer --format "$(bc -l <<<"$btc_rub")"
  };;
  bitstamp|bittrex|coinbase|gemini|kraken) {
    btc_usdt=$(setzer price btcusd "$1")
    #can't replace with internal usdt_usd model due to recursion
    usd_rub=$(setzer price usdrub)
    setzer --format "$(bc -l <<<"$btc_usdt * $usd_rub")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac

