#!/usr/bin/env bash
set -e
pair=usdrub
sources=(
  exchangeratesapi
  cbr
  ratesapi
)

case $1 in
  exchangeratesapi|cbr|ratesapi) {
    setzer x-price "$1" usdrub
  };;
  *) {
    export SETZER_MIN_MEDIAN=2
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
